// Platform Architecture Layer — Slice 1A. Single source of truth for brand/market/product/nav/
// footer/CTA/SEO/feature-flag/rollout/design-token config. Consumed via usePlatform(); wired into
// the live UI from App.jsx. See CLAUDE.md for the architecture decisions behind this file.

import type {
  BrandConfig,
  Market,
  ProductModuleEntry,
  NavigationItem,
  CtaLabels,
  FooterConfig,
  SeoConfig,
  FeatureFlags,
  RolloutConfig,
  DesignTokens,
} from "./types";
import { MARKET_STATUS, PRODUCT_STATUS } from "./constants";

export const BRAND: BrandConfig = {
  mission: "Building the Infrastructure for Accountable Democracy.",
  brandPromise: "Track Every Mandate. Measure Every Voice. Hold Leaders Accountable.",
  marketPosition: "The Pulse of {country} Democracy.",
  rolloutMessage: "Launching across Nigeria, expanding one community at a time.",
  values: [
    "Independent",
    "Transparent",
    "Citizen Powered",
    "Privacy First",
    "Methodology Driven",
    "Data Informed",
  ],
};

export const CURRENT_MARKET_CODE = "NG";

export const MARKETS: Market[] = [
  { code: "NG", name: "Nigeria", status: MARKET_STATUS.CURRENT },
  { code: "KE", name: "Kenya", status: MARKET_STATUS.FUTURE },
  { code: "GH", name: "Ghana", status: MARKET_STATUS.FUTURE },
  { code: "ZA", name: "South Africa", status: MARKET_STATUS.FUTURE },
];

// path: the real URL this product renders at, for products with a standalone nav destination.
// Citizen Pulse / Approval Ratings are real, live mechanisms (rep voting) but live inside the
// Representatives page rather than as their own destination, so they have no `path`.
export const PRODUCTS: ProductModuleEntry[] = [
  { key: "representatives", label: "Representatives", status: PRODUCT_STATUS.LIVE, path: "/" },
  { key: "pulseMap", label: "PulseMap™", status: PRODUCT_STATUS.LIVE, path: "/pulsemap" },
  { key: "demands", label: "Demands", status: PRODUCT_STATUS.LIVE, path: "/demands" },
  { key: "discussions", label: "Discussions", status: PRODUCT_STATUS.LIVE, path: "/discussion" },
  { key: "citizenPulse", label: "Citizen Pulse", status: PRODUCT_STATUS.LIVE },
  { key: "approvalRatings", label: "Approval Ratings", status: PRODUCT_STATUS.LIVE },
  { key: "insights", label: "Insights", status: PRODUCT_STATUS.UNRELEASED },
  { key: "pulseReports", label: "Pulse Reports", status: PRODUCT_STATUS.UNRELEASED },
  { key: "pulseRankings", label: "Pulse Rankings", status: PRODUCT_STATUS.UNRELEASED },
  { key: "pulseIndex", label: "Pulse Index", status: PRODUCT_STATUS.UNRELEASED },
  { key: "openCivicApi", label: "Open Civic API", status: PRODUCT_STATUS.UNRELEASED },
  { key: "researchCentre", label: "Research Centre", status: PRODUCT_STATUS.UNRELEASED },
  { key: "developerPlatform", label: "Developer Platform", status: PRODUCT_STATUS.UNRELEASED },
  { key: "analyticsSuite", label: "Analytics Suite", status: PRODUCT_STATUS.UNRELEASED },
];

// Election Watch is intentionally absent — it's injected at render time in App.jsx only when the
// live, Supabase-backed Election Mode flag is on. A static list here would fight that toggle.
export const NAVIGATION: NavigationItem[] = PRODUCTS.filter(
  (p) => p.status === PRODUCT_STATUS.LIVE && p.path
).map((p) => ({ key: p.key, label: p.label, path: p.path as string }));

export const CTA_LABELS: CtaLabels = {
  signInSignUp: "Join the Pulse",
  signOut: "Sign out",
  fileADemand: "File a demand",
  startADiscussion: "Start a discussion",
  // No current call site for the four below — defined now so components never hardcode these
  // labels once a real use appears (e.g. a future marketing landing page).
  exploreRepresentatives: "Explore Representatives",
  explorePulseMap: "Explore PulseMap™",
  viewInsights: "View Insights",
  subscribe: "Subscribe",
  readReport: "Read Report",
  learnMore: "Learn More",
};

export const FOOTER: FooterConfig = {
  // Kept verbatim from the existing footer — factual/methodology text, not marketing copy.
  disclaimer:
    "MANDATEWATCH — prototype build. Representative names, parties, and constituencies are real, sourced from nass.gov.ng and Wikipedia's Nigeria Governors' Forum page. Approval, felt-presence, and demand data are generated by platform users, not scraped. Directory coverage is partial — see project notes for gaps.",
  columns: [
    {
      title: "Platform",
      links: NAVIGATION.map((n) => ({ label: n.label, path: n.path })),
    },
    // Resources/Company/Support/Legal have no real destinations yet in this router-less SPA —
    // left empty rather than filled with dead links. See CLAUDE.md decision 2.
    { title: "Resources", links: [] },
    { title: "Company", links: [] },
    { title: "Support", links: [] },
    { title: "Legal", links: [] },
  ],
  social: [],
};

// Source of truth for index.html's <title>/meta tags — that file is generated at build time with
// no templating mechanism in this router-less Vite SPA, so it's kept in sync by hand. See the
// matching comment in index.html.
export const SEO: SeoConfig = {
  title: "MandateWatch — The Pulse of Nigerian Democracy",
  description:
    "Track every mandate. Measure every voice. Hold leaders accountable. MandateWatch is Nigeria's civic accountability platform for representative performance, citizen demands, and democratic participation.",
  keywords: [
    "Nigeria",
    "civic accountability",
    "elected officials",
    "representatives",
    "approval ratings",
    "citizen demands",
    "democracy",
  ],
  siteUrl: "https://mandatewatch.vercel.app",
  twitterCard: "summary",
};

// Genuinely unbuilt future toggles only — Election Mode already has a real, live, Supabase-backed
// implementation and is deliberately not duplicated here (see types.ts).
export const FEATURE_FLAGS: FeatureFlags = {
  pulseMap: true,
  reports: false,
  api: false,
  notifications: false,
  ninVerification: false,
  darkMode: false,
  realtimeUpdates: false,
  aiInsights: false,
};

export const ROLLOUT: RolloutConfig = {
  market: "Nigeria",
  launchStrategyMessage: "Launching across Nigeria, expanding one community at a time.",
};

// Mirrors the real design tokens already live in App.jsx's inline <style> :root block
// (App.jsx:2277-2286) — interpolated back in there so a future rebrand only touches this file.
export const DESIGN_TOKENS: DesignTokens = {
  colors: {
    ink: "#1B2A3A",
    inkSoft: "#4A5A66",
    verdant: "#1F5E3F",
    verdantDark: "#143D29",
    brass: "#A9791F",
    brassSoft: "#D9B45C",
    // A darker variant specifically for small brass TEXT (badges/CTAs) -- the base --brass value
    // fails WCAG AA (~3.2-3.6:1) at typical UI text sizes; this passes (~5.2-5.8:1) while staying
    // in the same brass/gold hue family, mirroring the existing --verdant-dark pattern. Found via
    // a real axe DevTools scan during Slice 1D — see CLAUDE.md.
    brassDark: "#7F5B17",
    rust: "#A6432E",
    paper: "#EEF0E6",
    paperCard: "#F7F8F2",
    line: "#CBCFC0",
  },
  typography: {
    heading: "'Archivo', sans-serif",
    body: "'Inter', sans-serif",
    mono: "'IBM Plex Mono', monospace",
  },
};
